# Optimized for low-resource servers
worker_processes 1;

server {
    listen 80;
    server_name camtool.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name camtool.site;

    ssl_certificate /etc/letsencrypt/live/camtool.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/camtool.site/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://server:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
